kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.namespace.name }}-full-access-role
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["*"]